<div class="hero-unit">
<h1>Formulario Recibe</h1>
<h2>
<?php
//print_r($_POST);
?>
</h2>
<ul>
	<li>Nombre: <?php echo $this->datos['nombre'] ?></li>
	<li>Apellido: <?php echo $this->datos['apellido'] ?></li>
	<li>Pass: <?php echo $this->datos['pass'] ?></li>
	<li>Foto: <?php echo $this->datos['foto'] ?></li>
	<li>Genero: <?php echo $this->datos['genero'] ?></li>
	<li>Idioma: <?php echo $this->datos['idioma'] ?></li>

</ul>
</div>
