
<div data-type="template" class="tpl">
  <div id="thumbView"><a title="{{title}}" href="javascript:;" class="remove"></a>{{src}}<span class="main">{{main}}</span></div>
  <div id="urlVideoView"><a href="http://www.youtube.com/watch?v={{vid}}" target="_blank" title="{{title}}"><img alt="{{title}}" data-src="{{preview}}" width="{{width}}" height="{{height}}"/></a><a href="http://www.youtube.com/watch?v={{vid}}" target="_blank" title="{{title}}">{{title}}</a><a href="javascript:;" title="Eliminar" class="remove">Eliminar</a></div>
</div>