
<div data-type="template" class="tpl">
  <div id="thumbView"><a title="{{title}}" href="javascript:;" class="remove"></a>{{src}}<span class="main">{{main}}</span></div>
  <!--http://gdata.youtube.com/feeds/api/videos/R9UW3e30udM?v=2&alt=json-in-script&callback=youtubeFeedCallback-->
  <!--120px x 90px-->
  <div id="urlVideoView"><a href="http://www.youtube.com/watch?v={{vid}}" target="_blank" title="{{title}}">{{title}}</a></div>
</div>