
<div class="head-ads">
  <h2><?php echo $this->title ?></h2>
</div>
<div class="row">
  <div class="to-right"><a href="javascript:;" title="Añadir RUC" class="btn-urb">Añadir RUC</a></div>
</div>
<table class="table mt20 mb30">
  <thead>
    <tr>
      <th class="tw50">#</th>
      <th class="tw200"> <span class="tbl-arrows"> Fecha de Registro</span><span class="arrows"><a href="javascript:;" title="Down" class="down">Down</a><a href="javascript:;" title="Up" class="up">Up</a></span></th>
      <th class="tw140">RUC</th>
      <th class="tw410">Razón Social</th>
      <th class="tw90">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>01/11/2012  &nbsp;|&nbsp;  10:25:01</td>
      <td>20123456789</td>
      <td class="tlbleft">Panchita Inmobiliaria SAC</td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td>2</td>
      <td>01/11/2012  &nbsp;|&nbsp;  10:25:01</td>
      <td>20123456789</td>
      <td class="tlbleft">Panchita Inmobiliaria SAC</td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td>3</td>
      <td>01/11/2012  &nbsp;|&nbsp;  10:25:01</td>
      <td>20123456789</td>
      <td class="tlbleft">Condominios Panchita SAC</td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td>4</td>
      <td>01/11/2012  &nbsp;|&nbsp;  10:25:01</td>
      <td>20123456789</td>
      <td class="tlbleft">Panchita Inmobiliaria SAC</td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
  </tbody>
</table>
<div class="head-ads">
  <h2>Nuevo Registro de Facturación</h2>
</div>
<div class="box-white mg0">
  <form id="formAlert" method="post" action="" class="formAlert">
    <h3 class="mb30">Los campos con <span class="red">* </span>son obligatorios</h3>
    <div class="control-group">
      <div class="cgroup-inline">
        <div class="control-group">
          <label class="control-label"> <span class="red">*</span>RUC:</label>
          <input id="txtRuc" name="txtRuc" type="text" class="input-standar"/>
        </div>
        <div class="control-group">
          <label class="control-label"><span class="red">*</span>Razón Social:</label>
          <input id="txtRazonsocial" name="txtRazonsocial" type="text" class="input-medium"/>
        </div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Dirección:</label>
      <input id="txtDireccion" name="txtDireccion" type="text" class="input-large"/>
    </div>
    <div class="control-group mb20">
      <div class="cgroup-inline">
        <div class="control-group">
          <label class="control-label">Departamento:</label>
          <div class="controls">
            <select>
              <option> </option>
              <option>Departamento</option>
              <option>Departamento</option>
            </select>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">Provincia:</label>
          <div class="controls">
            <select>
              <option> </option>
              <option>Departamento</option>
              <option>Departamento</option>
            </select>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">Distrito:</label>
          <div class="controls">
            <select>
              <option> </option>
              <option>Departamento</option>
              <option>Departamento</option>
            </select>
          </div>
        </div>
      </div>
    </div>
  </form>
  <div class="control"><a href="javascript:;" title="Guardar" class="btn-urb btn-medium">Guardar</a></div>
</div>