
<div class="head-ads">
  <h2 class="nofloat"><?php echo $this->title ?></h2>
  <form id="frmSearch" class="search-titems">
    <div class="controls">
      <input type="text" name="txtSearch" id="txtSearch" placeholder="Busca por Nombre del Aviso"/>
    </div>
    <div class="controls">
      <button type="submit" class="btn-urb btn-small">Buscar</button>
    </div>
  </form>
</div>
<div class="cgroup-inline mb20">
  <div class="control-group">
    <select class="select-mini">
      <option>falta</option>
      <option>Todo</option>
      <option>Nada</option>
    </select>
  </div>
  <div class="control-group mleft10"><a href="javascript:;" title="Eliminar" class="btn-gray btn-small">Eliminar</a><a href="javascript:;" title="Exportar a Excel" class="btn-gray btn-small">Exportar a Excel</a></div>
  <div class="to-right"><a href="javascript:;" title="Agregar Contacto" class="btn-urb">Agregar Contacto</a></div>
</div>
<table class="table">
  <thead>
    <tr>
      <th class="tw270"> <span class="tbl-arrows">Nombre</span><span class="arrows"><a href="javascript:;" title="Down" class="down">Down</a><a href="javascript:;" title="Up" class="up">Up</a></span></th>
      <th class="tw200"> <span class="tbl-arrows">Email</span><span class="arrows"><a href="javascript:;" title="Down" class="down">Down</a><a href="javascript:;" title="Up" class="up">Up</a></span></th>
      <th class="tw130"> <span class="tbl-arrows">Teléfono</span><span class="arrows"><a href="javascript:;" title="Down" class="down">Down</a><a href="javascript:;" title="Up" class="up">Up</a></span></th>
      <th class="tw130"> <span class="tbl-arrows">Celular</span><span class="arrows"><a href="javascript:;" title="Down" class="down">Down</a><a href="javascript:;" title="Up" class="up">Up</a></span></th>
      <th class="tw160">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tbl-option"> 
        <label for="chkName"> </label>
        <input id="chkName" name="chkName" type="checkbox"/>Alejandro David Monteros Palacios
      </td>
      <td>rgutierrez@outlook.com</td>
      <td>4368595</td>
      <td>999888777</td>
      <td><a href="javascript:;" title="Ver Datos" class="action-icons property">Ver Datos</a><a href="javascript:;" title="Enviar mail a Contacto" class="action-icons message">Enviar mail a Contacto</a><a href="javascript:;" title="Agendar Cita" class="action-icons calendar">Agendar Cita</a><a href="javascript:;" title="Agregar Notas" class="action-icons note">Agregar Notas</a><a href="javascript:;" title="Eliminar" class="action-icons clean">Eliminar</a></td>
    </tr>
  </tbody>
</table><a href="javascript:;" title="Ver más Contactos" class="btn-vermas">Ver más Contactos</a>