
<div class="head-ads">
  <h2 class="nofloat">Mis Avisos Activos</h2>
  <form id="frmSearch" class="search-titems">
    <div class="controls">
      <input type="text" name="txtSearch" id="txtSearch" placeholder="Busca por Nombre del Aviso"/>
    </div>
    <div class="controls">
      <button type="submit" class="btn-urb btn-small">Buscar</button>
    </div>
  </form>
</div>
<table class="table">
  <thead>
    <tr>
      <th class="tw160"> </th>
      <th class="tw260">Aviso</th>
      <th class="tw140">Registro</th>
      <th class="tw90">Caducidad</th>
      <th class="tw140">Tipo</th>
      <th class="tw90">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="tw160"><a href="javascript:;" title="Urbania"><img src="/img/1.png" alt="Urbania"/></a></td>
      <td> 
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa" class="lnk-green">Venta de Casa en Punta Hermosa</a></h3><a href="javascript:;" title="Visitas" class="numbers"><span class="numbers-ico sight"></span>124</a>
      </td>
      <td>11 de Diciembre del 2013</td>
      <td>En 5 días</td>
      <td>
         
        Paquete Simple Plus<br><a href="javascript:;" title="Mejora tu aviso" class="lnk-green">Mejora tu aviso</a>
      </td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Mejora tu Aviso" class="action-icons improve">Mejora tu Aviso</a><a href="javascript:;" title="Dar de Baja" class="action-icons unsubscribe">Dar de Baja</a></td>
    </tr>
    <tr>
      <td class="tw160"><a href="javascript:;" title="Urbania"><img src="/img/1.png" alt="Urbania"/></a></td>
      <td> 
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa" class="lnk-green">Venta de Casa en Punta Hermosa</a></h3><a href="javascript:;" title="Visitas" class="numbers"><span class="numbers-ico sight"></span>124</a>
      </td>
      <td>11 de Marzo del 2013</td>
      <td>En 5 días</td>
      <td>
         
        Paquete Simple<br><a href="javascript:;" title="Mejora tu aviso" class="lnk-green">Mejora tu aviso</a>
      </td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Mejora tu Aviso" class="action-icons improve">Mejora tu Aviso</a><a href="javascript:;" title="Dar de Baja" class="action-icons unsubscribe">Dar de Baja</a></td>
    </tr>
    <tr>
      <td class="tw160"><a href="javascript:;" title="Urbania"><img src="/img/1.png" alt="Urbania"/></a></td>
      <td> 
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa" class="lnk-green">Venta de Casa en Punta Hermosa</a></h3><a href="javascript:;" title="Visitas" class="numbers"><span class="numbers-ico sight"></span>124</a>
      </td>
      <td>11 de Marzo del 2013</td>
      <td>En 5 días</td>
      <td>Paquete Premium<br><span class="lnk-blue">Al impreso el<br>21 de Marzo del 2013</span></td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Mejora tu Aviso" class="action-icons improve">Mejora tu Aviso</a><a href="javascript:;" title="Dar de Baja" class="action-icons unsubscribe">Dar de Baja</a></td>
    </tr>
    <tr>
      <td class="tw160"><a href="javascript:;" title="Urbania"><img src="/img/1.png" alt="Urbania"/></a></td>
      <td> 
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa" class="lnk-green">Venta de Casa en Punta Hermosa</a></h3><a href="javascript:;" title="Visitas" class="numbers"><span class="numbers-ico sight"></span>124</a>
      </td>
      <td>11 de Marzo del 2013</td>
      <td>En 5 días</td>
      <td>
         
        Paquete Simple<br><a href="javascript:;" title="Mejora tu aviso" class="lnk-green">Mejora tu aviso</a>
      </td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Mejora tu Aviso" class="action-icons improve">Mejora tu Aviso</a><a href="javascript:;" title="Dar de Baja" class="action-icons unsubscribe">Dar de Baja</a></td>
    </tr>
    <tr>
      <td class="tw160"><a href="javascript:;" title="Urbania"><img src="/img/1.png" alt="Urbania"/></a></td>
      <td> 
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa" class="lnk-green">Venta de Casa en Punta Hermosa</a></h3><a href="javascript:;" title="Visitas" class="numbers"><span class="numbers-ico sight"></span>124</a>
      </td>
      <td>11 de Marzo del 2013</td>
      <td>En 5 días</td>
      <td>Paquete Gold<br><a href="javascript:;" title="Mejora tu aviso" class="lnk-green">Mejora tu aviso</a></td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Mejora tu Aviso" class="action-icons improve">Mejora tu Aviso</a><a href="javascript:;" title="Dar de Baja" class="action-icons unsubscribe">Dar de Baja</a></td>
    </tr>
    <tr>
      <td class="tw160"><a href="javascript:;" title="Urbania"><img src="/img/1.png" alt="Urbania"/></a></td>
      <td> 
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa" class="lnk-green">Venta de Casa en Punta Hermosa</a></h3><a href="javascript:;" title="Visitas" class="numbers"><span class="numbers-ico sight"></span>124</a>
      </td>
      <td>11 de Marzo del 2013</td>
      <td>En 5 días</td>
      <td>Paquete Simple<br><span class="lnk-blue">Al impreso el<br>21 de Marzo del 2013</span></td>
      <td><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Mejora tu Aviso" class="action-icons improve">Mejora tu Aviso</a><a href="javascript:;" title="Dar de Baja" class="action-icons unsubscribe">Dar de Baja</a></td>
    </tr>
  </tbody>
</table><a href="javascript:;" title="Ver más Avisos" class="btn-vermas">Ver más Avisos</a>