
<div class="head-adm">
  <h2>Mis Avisos de Baja</h2>
  <form id="frmSearch" class="filter-adm">
    <div class="controls">
      <input type="text" name="txtSearch" id="txtSearch" placeholder="Busca por Nombre del Aviso"/>
      <label for="txtSearch" class="vglass"></label>
    </div>
    <div class="controls">
      <button type="submit" class="btn-urb btn-small">Buscar</button>
    </div>
  </form>
</div>
<div class="opts-hadmin row"><a href="javascript:;" title="Eliminar Avisos" class="btn-urb">Eliminar Avisos</a></div>
<table class="tbl-admin">
  <thead>
    <tr>
      <th class="tdCheck">
        <input id="chkAviso" name="chkAviso" type="checkbox"/>
      </th>
      <th class="tdImgAds"></th>
      <th class="tdAds tw241">Aviso</th>
      <th class="tdRegister">Registro</th>
      <th class="tdExpire">Caducidad</th>
      <th class="tdTypPacket">Tipo</th>
      <th class="tdAcc3">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="tdCheck">
        <input id="chkAviso" name="chkAviso" type="checkbox"/>
      </td>
      <td class="tdImgAds"><a href="javascript:;" title="Urbania"><img src="images/1.png" alt="Urbania" width="160" height="90"/></a></td>
      <td class="tdAds tw241">
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa">Venta de Casa en Punta Hermosa</a></h3><span class="infview"><span></span>124</span>
      </td>
      <td class="tdRegister">11 de Diciembre del 2013</td>
      <td class="tdExpire">En 5 días</td>
      <td class="tdTypPacket">Paquete Simple Plus</td>
      <td class="tdAcc3"><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Actualizar" class="action-icons republish">actualizar</a><a href="javascript:;" title="Eliminar" class="action-icons delete">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tdCheck">
        <input id="chkAviso" name="chkAviso" type="checkbox"/>
      </td>
      <td class="tdImgAds"><a href="javascript:;" title="Urbania"><img src="images/1.png" alt="Urbania" width="160" height="90"/></a></td>
      <td class="tdAds tw241">
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa">Venta de Casa en Punta Hermosa</a></h3><span class="infview"><span></span>124</span>
      </td>
      <td class="tdRegister">11 de Marzo del 2013</td>
      <td class="tdExpire">En 5 días</td>
      <td class="tdTypPacket">Paquete Simple</td>
      <td class="tdAcc3"><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Actualizar" class="action-icons republish">actualizar</a><a href="javascript:;" title="Eliminar" class="action-icons delete">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tdCheck">
        <input id="chkAviso" name="chkAviso" type="checkbox"/>
      </td>
      <td class="tdImgAds"><a href="javascript:;" title="Urbania"><img src="images/1.png" alt="Urbania" width="160" height="90"/></a></td>
      <td class="tdAds tw241">
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa">Venta de Casa en Punta Hermosa</a></h3><span class="infview"><span></span>124</span>
      </td>
      <td class="tdRegister">11 de Marzo del 2013</td>
      <td class="tdExpire">En 5 días</td>
      <td class="tdTypPacket">Paquete Premium<br><span class="infprint">Al impreso el<br>21 de Marzo del 2013</span></td>
      <td class="tdAcc3"><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Actualizar" class="action-icons republish">actualizar</a><a href="javascript:;" title="Eliminar" class="action-icons delete">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tdCheck">
        <input id="chkAviso" name="chkAviso" type="checkbox"/>
      </td>
      <td class="tdImgAds"><a href="javascript:;" title="Urbania"><img src="images/1.png" alt="Urbania" width="160" height="90"/></a></td>
      <td class="tdAds tw241">
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa">Venta de Casa en Punta Hermosa</a></h3><span class="infview"><span></span>124</span>
      </td>
      <td class="tdRegister">11 de Marzo del 2013</td>
      <td class="tdExpire">En 5 días</td>
      <td class="tdTypPacket">Paquete Simple</td>
      <td class="tdAcc3"><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Actualizar" class="action-icons republish">actualizar</a><a href="javascript:;" title="Eliminar" class="action-icons delete">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tdCheck">
        <input id="chkAviso" name="chkAviso" type="checkbox"/>
      </td>
      <td class="tdImgAds"><a href="javascript:;" title="Urbania"><img src="images/1.png" alt="Urbania" width="160" height="90"/></a></td>
      <td class="tdAds tw241">
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa">Venta de Casa en Punta Hermosa</a></h3><span class="infview"><span></span>124</span>
      </td>
      <td class="tdRegister">11 de Marzo del 2013</td>
      <td class="tdExpire">En 5 días</td>
      <td class="tdTypPacket">Paquete Gold</td>
      <td class="tdAcc3"><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Actualizar" class="action-icons republish">actualizar</a><a href="javascript:;" title="Eliminar" class="action-icons delete">Eliminar</a></td>
    </tr>
    <tr>
      <td class="tdCheck">
        <input id="chkAviso" name="chkAviso" type="checkbox"/>
      </td>
      <td class="tdImgAds"><a href="javascript:;" title="Urbania"><img src="images/1.png" alt="Urbania" width="160" height="90"/></a></td>
      <td class="tdAds tw241">
        <h3><a href="javascript:;" title="Venta de Casa en Punta Hermosa">Venta de Casa en Punta Hermosa</a></h3><span class="infview"><span></span>124</span>
      </td>
      <td class="tdRegister">11 de Marzo del 2013</td>
      <td class="tdExpire">En 5 días</td>
      <td class="tdTypPacket">Paquete Simple</td>
      <td class="tdAcc3"><a href="javascript:;" title="Editar" class="action-icons edit">editar</a><a href="javascript:;" title="Actualizar" class="action-icons republish">actualizar</a><a href="javascript:;" title="Eliminar" class="action-icons delete">Eliminar</a></td>
    </tr>
  </tbody>
</table><a href="javascript:;" title="Ver más Avisos" class="btn-vermas">Ver más Avisos</a>