
<h2>Fotos
  <div id="divGallery" class="white-box">
    <div class="dragger"><span class="note">Suelta tus imágenes aquí <small>Máximo 2 MB por imágen.</small></span></div>
    <div class="options">
      <input type="text" id="file" name="file" placeholder="No ha elegido ningún archivo"/>
      <button type="button" id="btnChoose">Elige tu imagen</button>
    </div>
    <form name="demoFiler" id="demoFiler" enctype="multipart/form-data">
      <fielset>
        <input type="file" name="multiUpload" id="multiUpload" multiple="multiple"/>
        <input type="submit" name="submitHandler" id="submitHandler" value="Upload"/>
      </fielset>
    </form>
  </div>
</h2>