
<div class="head-ads">
  <h2 class="nofloat font24">Publicar: Paso <?php echo $this->id ?> - Llena los datos del aviso</h2><span class="text-detail">Llena los datos de tu aviso</span>
  <ul class="steps">
    <li>Escoge<br> el Aviso</li>
    <li class="act">Datos<br> del Aviso</li>
    <li>Aviso<br>Impreso</li>
    <li>Verifica<br> tus datos</li>
  </ul>
</div>
<div class="head-ads">
  <h2>Datos de Aviso</h2>
</div>
<div class="box-white">
  <div class="cgroup-inline">
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Transacción:</label>
      <div class="controls">
        <select>
          <option>Venta</option>
          <option>Alquiler Turista</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Localizado en:</label>
      <div class="controls">
        <select>
          <option>Ciudad</option>
          <option>Campo</option>
          <option>Playa</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Tipo de Inmueble:</label>
      <div class="controls">
        <select>
          <option>Casa</option>
          <option>Departamento</option>
          <option>Mini Departamento</option>
          <option>Terreno</option>
          <option>Oficina</option>
          <option>Tiendas o Locales</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Moneda:</label>
      <div class="controls">
        <select class="select-supermini">
          <option>Soles</option>
          <option>Departamento</option>
          <option>Departamento</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Precio.<span class="textgray">TC: S/.2.55</span></label>
      <div class="controls">
        <input id="txtPrice" name="txtPrice" type="text" class="input-small"/>
      </div>
    </div>
  </div>
  <div class="cgroup-inline">
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Dormitorios:</label>
      <div class="controls">
        <select class="select-medium">
          <option>0</option>
          <option>1</option>
          <option>2</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Baños:</label>
      <div class="controls">
        <select class="select-medium">
          <option>0</option>
          <option>1</option>
          <option>2</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Medio Baño:</label>
      <div class="controls">
        <select class="select-medium">
          <option>0</option>
          <option>1</option>
          <option>2</option>
          <option>3</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Estacionamiento:</label>
      <div class="controls">
        <select class="select-medium">
          <option>0</option>
          <option>1</option>
          <option>2</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Años de Antigüedad:</label>
      <div class="controls">
        <select class="select-medium">
          <option>0</option>
          <option>1</option>
          <option>2</option>
        </select>
      </div>
    </div>
  </div>
  <div class="cgroup-inline">
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Área Terreno:</label>
      <div class="controls">
        <input id="txtAreaterreno" name="txtAreaterreno" type="text" class="input-small"/><span class="help-inline">m2</span>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Área Construida:</label>
      <div class="controls">
        <input id="txtAreaconstruida" name="txtAreaconstruida" type="text" class="input-small"/><span class="help-inline">m2</span>
      </div>
    </div>
  </div>
  <div class="cgroup-inline">
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Teléfono de contacto 1:</label>
      <div class="controls">
        <input id="txtPhone" name="txtPhone" type="text" class="input-standar"/>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Teléfono de contacto 1:</label>
      <div class="controls">
        <input id="txtPhone" name="txtPhone" type="text" class="input-standar"/>
      </div>
    </div>
  </div>
  <div class="box-hidden">
    <div class="cgroup-inline">
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Transacción:</label>
        <div class="controls">
          <select>
            <option>Venta</option>
            <option>Alquiler Turista</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Localizado en:</label>
        <div class="controls">
          <select>
            <option>Ciudad</option>
            <option>Campo</option>
            <option>Playa</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Tipo de Inmueble:</label>
        <div class="controls">
          <select>
            <option>Casa</option>
            <option>Departamento</option>
            <option>Mini Departamento</option>
            <option>Terreno</option>
            <option>Oficina</option>
            <option>Tiendas o Locales</option>
          </select>
        </div>
      </div>
    </div>
    <div class="cgroup-inline">
      <div class="control-group">
        <label class="control-label">Moneda:<span class="textgray">TC: S/.2.55</span></label>
        <div class="controls">
          <select class="select-small">
            <option>Soles</option>
            <option>Dolares</option>
            <option>Euros</option>
            <option>Libras</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Alquiler Mensual:</label>
        <div class="controls">
          <input id="txtMonthly" name="txtMonthly" type="text" class="input-small"/>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Alquiler Semanal:</label>
        <div class="controls">
          <input id="txtWeekly" name="txtWeekly" type="text" class="input-small"/>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Alquiler Diario:</label>
        <div class="controls">
          <input id="txtDaily" name="txtDaily" type="text" class="input-small"/>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Semana Santa:</label>
        <div class="controls">
          <input id="txtStweek" name="txtStweek" type="text" class="input-small"/>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Año Nuevo:</label>
        <div class="controls">
          <input id="txtNewyear" name="txtNewyear" type="text" class="input-small"/>
        </div>
      </div>
    </div>
    <div class="cgroup-inline">
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Dormitorios:</label>
        <div class="controls">
          <select class="select-medium">
            <option>0</option>
            <option>1</option>
            <option>2</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Baños:</label>
        <div class="controls">
          <select class="select-medium">
            <option>0</option>
            <option>1</option>
            <option>2</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Medio Baño:</label>
        <div class="controls">
          <select class="select-medium">
            <option>0</option>
            <option>1</option>
            <option>2</option>
            <option>3</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Estacionamiento:</label>
        <div class="controls">
          <select class="select-medium">
            <option>0</option>
            <option>1</option>
            <option>2</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Años de Antigüedad:</label>
        <div class="controls">
          <select class="select-medium">
            <option>0</option>
            <option>1</option>
            <option>2</option>
          </select>
        </div>
      </div>
    </div>
    <div class="cgroup-inline">
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Área Terreno:</label>
        <div class="controls">
          <input id="txtAreaterreno" name="txtAreaterreno" type="text" class="input-small"/><span class="help-inline">m2</span>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Área Construida:</label>
        <div class="controls">
          <input id="txtAreaconstruida" name="txtAreaconstruida" type="text" class="input-small"/><span class="help-inline">m2</span>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Tipo Estadía:</label>
        <div class="controls">
          <select class="select-medium">
            <option>Viajero</option>
            <option>1</option>
            <option>2</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label"><span class="red">*</span>Teléfono de contacto 1:</label>
        <div class="controls">
          <input id="txtPhone" name="txtPhone" type="text" class="input-standar"/>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Teléfono de contacto 1:</label>
        <div class="controls">
          <input id="txtPhone" name="txtPhone" type="text" class="input-standar"/>
        </div>
      </div>
    </div>
    <div class="cgroup-inline">
      <label class="control-label">Fechas Disponibles:</label>
      <div class="controls">
        <input id="txtPhone" name="txtPhone" type="text" class="input-extralarge"/>
      </div>
    </div>
  </div>
  <div class="control-group">
    <div class="to-right red">Te quedan 53 de 1200 caracteres</div>
    <label class="control-label">Descripción:</label>
    <div class="controls-line">
      <textarea id="txtDescription" name="txtDescription" type="textarea" class="textarea-extralarge"></textarea>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Tags del Aviso:</label>
    <div class="controls-line">
      <div class="controls">
        <input id="txtTags" name="txtTags" type="text" class="input-extralarge"/>
      </div>
    </div>
  </div>
  <p class="details">Ingresa palabras claves que identifiquen a tu aviso, así será más fácil para los usuarios encontrar tu anuncio. Ingresa las palabras separadas por comas (,).</p>
</div>
<div class="head-ads">
  <h2>Ubicación</h2>
</div>
<div class="box-white">
  <div class="cgroup-inline">
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Departamento:</label>
      <div class="controls">
        <select>
          <option>- Seleccionar -</option>
          <option>Lima</option>
          <option>Departamento</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Provincia:</label>
      <div class="controls">
        <select>
          <option>- Seleccionar -</option>
          <option>Departamento</option>
          <option>Departamento</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><span class="red">*</span>Distrito:</label>
      <div class="controls">
        <select>
          <option>- Seleccionar -</option>
          <option>Departamento</option>
          <option>Departamento</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Urbanización:</label>
      <div class="controls">
        <select>
          <option>- Seleccionar -</option>
          <option>Departamento</option>
          <option>Departamento</option>
        </select>
      </div>
    </div>
  </div>
  <div class="control-group">
    <div class="cgroup-inline">
      <div class="control-group">
        <label class="control-label">Vía:</label>
        <div class="controls">
          <select class="select-small">
            <option>Avenida</option>
            <option>Avenida</option>
            <option>Avenida</option>
          </select>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Nombre de la Vía:</label>
        <div class="controls">
          <input id="txtVia" name="txtVia" type="text" class="input-xmedium"/>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Número:</label>
        <div class="controls">
          <input id="txtNumber" name="txtNumber" type="text" class="input-xmini"/>
        </div>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Referencias:</label>
    <div class="controls-line">
      <div class="controls">
        <input id="txtReference" name="txtReference" type="text" class="input-extralarge"/>
      </div>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label">Arrastre el marcador rojo en la ubicación en donde se encuentra su inmueble:</label>
    <div class="map">
      <div id="map-canvas"></div>
    </div>
  </div>
</div>
<div class="head-ads">
  <h2>Fotos</h2>
</div>
<div id="divImageGallery" class="box-white">
  <div class="dragger"><span class="note">Suelta tus imágenes aquí<small>Máximo 2 MB por imágen.</small></span></div>
  <div class="options">
    <input type="text" id="file" name="file" placeholder="No ha elegido ningún archivo"/>
    <button type="button" id="btnChoose" class="btn-urb btn-small">Elige tu imagen</button>
  </div>
</div>
<div class="head-ads">
  <h2>Videos</h2>
</div>
<div id="divVideoGallery" class="box-white">
  <div class="control-group">
    <div class="cgroup-inline">
      <div class="control-group">
        <label class="control-label">Añadir Video:</label>
        <div class="controls">
          <input placeholder="Ingrese la url del video" id="txtVideo" name="txtVideo" type="text" class="input-large"/>
        </div>
      </div>
      <div class="control-group">
        <label>&nbsp;</label>
        <div class="controls">
          <button type="button" id="btnAddVideo" class="btn-urb btn-small">Agregar Video</button>
        </div>
      </div>
      <p class="details">Ingresa la URL del video. Ejemplo: http://www.youtube.com/watch?v=R9UW3e30udM</p>
    </div>
  </div>
  <ol id="olVideoList"></ol>
</div>
<div class="head-ads">
  <h2>Detalles Adicionales</h2>
</div>
<div class="box-white">
  <div class="control-group">
    <ul class="list-chk4 row">
      <li>
        <label for="chkAreadeport" class="ioption">
          <input id="chkAreadeport" name="chkAreadeport" type="checkbox"/>Área deportiva
        </label>
      </li>
      <li>
        <label for="chkTerraza" class="ioption">
          <input id="chkTerraza" name="chkTerraza" type="checkbox"/>Terraza
        </label>
      </li>
      <li>
        <label for="chkCable" class="ioption">
          <input id="chkCable" name="chkCable" type="checkbox"/>Cable
        </label>
      </li>
      <li>
        <label for="chkPortero" class="ioption">
          <input id="chkPortero" name="chkPortero" type="checkbox"/>Portero Eléctrico
        </label>
      </li>
      <li>
        <label for="chkPiscina" class="ioption">
          <input id="chkPiscina" name="chkPiscina" type="checkbox"/>Piscina
        </label>
      </li>
      <li>
        <label for="chkBano" class="ioption">
          <input id="chkBano" name="chkBano" type="checkbox"/>Baño Propio
        </label>
      </li>
      <li>
        <label for="chkAmoblado" class="ioption">
          <input id="chkAmoblado" name="chkAmoblado" type="checkbox"/>Amoblado
        </label>
      </li>
      <li>
        <label for="chkCocina" class="ioption">
          <input id="chkCocina" name="chkCocina" type="checkbox"/>Cocina con Repostero
        </label>
      </li>
      <li>
        <label for="chkDeposito" class="ioption">
          <input id="chkDeposito" name="chkDeposito" type="checkbox"/>Depósito
        </label>
      </li>
      <li>
        <label for="chkPatio" class="ioption">
          <input id="chkPatio" name="chkPatio" type="checkbox"/>Patio
        </label>
      </li>
      <li>
        <label for="chkClub" class="ioption">
          <input id="chkClub" name="chkClub" type="checkbox"/>Club House
        </label>
      </li>
      <li>
        <label for="chkWalkcloset" class="ioption">
          <input id="chkWalkcloset" name="chkWalkcloset" type="checkbox"/>Walk-in Closet
        </label>
      </li>
      <li>
        <label for="chkKitchenette" class="ioption">
          <input id="chkKitchenette" name="chkKitchenette" type="checkbox"/>Kitchenette
        </label>
      </li>
      <li>
        <label for="chkServicio" class="ioption">
          <input id="chkServicio" name="chkServicio" type="checkbox"/>Cuarto de servicio
        </label>
      </li>
      <li>
        <label for="chkIndependiente" class="ioption">
          <input id="chkIndependiente" name="chkIndependiente" type="checkbox"/>Independiente
        </label>
      </li>
      <li>
        <label for="chkCloset" class="ioption">
          <input id="chkCloset" name="chkCloset" type="checkbox"/>Closet
        </label>
      </li>
      <li>
        <label for="chkAreadeportiva" class="ioption">
          <input id="chkAreadeportiva" name="chkAreadeportiva" type="checkbox"/>Área BBQ
        </label>
      </li>
      <li>
        <label for="chkBanoserv" class="ioption">
          <input id="chkBanoserv" name="chkBanoserv" type="checkbox"/>Baño de Servicio
        </label>
      </li>
      <li>
        <label for="chkJacussi" class="ioption">
          <input id="chkJacussi" name="chkJacussi" type="checkbox"/>Jacuzzi
        </label>
      </li>
      <li>
        <label for="chkBalcon" class="ioption">
          <input id="chkBalcon" name="chkBalcon" type="checkbox"/>Balcón
        </label>
      </li>
      <li>
        <label for="chkInternet" class="ioption">
          <input id="chkInternet" name="chkInternet" type="checkbox"/>Internet
        </label>
      </li>
      <li>
        <label for="chkLavanderia" class="ioption">
          <input id="chkLavanderia" name="chkLavanderia" type="checkbox"/>Lavandería
        </label>
      </li>
      <li>
        <label for="chkJardin" class="ioption">
          <input id="chkJardin" name="chkJardin" type="checkbox"/>Jardín
        </label>
      </li>
      <li>
        <label for="chkVista" class="ioption">
          <input id="chkVista" name="chkVista" type="checkbox"/>Vista a la Calle
        </label>
      </li>
      <li>
        <label for="chkParque" class="ioption">
          <input id="chkParque" name="chkParque" type="checkbox"/>Frente a Parque
        </label>
      </li>
      <li>
        <label for="chkGuardian" class="ioption">
          <input id="chkGuardian" name="chkGuardian" type="checkbox"/>Caseta con Guardían exterior
        </label>
      </li>
    </ul>
  </div>
</div>
<div class="control"><a href="javascript:;" title="Regresar" class="btn-gray btn-medium">Regresar</a><a href="javascript:;" title="Continuar" class="btn-urb btn-medium">Continuar</a></div>
<div class="box-white"><?php echo $this->tplLoader(); ?></div>